language: node_js
group: travis_latest
os: linux
sudo: false

node_js:
  - stable
  - lts/carbon
  - lts/boron

cache:
  directories:
    - node_modules
before_cache: rm -rf node_modules/.cache

before_install:
  - npm install -g greenkeeper-lockfile
  - greenkeeper-lockfile-update

script:
  - npm run lint
  - npm run typecheck
  - npm run test -- --forbid-only --forbid-pending --timeout 20000

after_script: if [[ $GH_TOKEN ]]; then greenkeeper-lockfile-upload; fi;

after_success: cat ./coverage/lcov.info | coveralls

services:
  - mongodb

stages:
  - Test
  - name: &releaseStage Release
    if: tag IS present

jobs:
  include:
    - stage: *releaseStage
      services: []
      node_js: stable
      script: npm run build
      after_success: false
      before_install: false
      after_success: false
      before_deploy: node ./update-version.js
      deploy:
        - provider: npm
          on:
            tags: true
          skip_cleanup: true
          email: a.molcanovas@gmail.com
          api_key:
            secure: "D8D0XyBCa2HzM/tq9PrU8bYIp8sHaZCxYJhZOnyELJ+vPf39nKW1vyVa34jcOab1JVbXS/Y29vPtd03FGPXPRZABJcjkXxBNW9o7u4khDKqZ2Z/498gvSZAIpSNrQzBQNPzwM1WZ4Fit1FIG24lzLIHCrfFV6pPc+urC8C6IO10MUqkRhE0TfyouHCXQkd59oZL7u3pSY/LB70bId5Noq8Cmr2bloDIZFwy5bZq3Udm4WX/+tMiO9qTDcwfZGX0uFPwumFJw/xURGHmmrbn+qarbRDH6RNa2MHMgkime/f1vR1K9J+22m6MqpH0aZ30EaaUGsXuBNwDPSSTc2Y+9RQE6D5sTZzBdtpHKAXa0ACiCFte+x+SCypHBubquSU0gkO+CDBoohVFG4h7pocawsMMfR5+IOKnBxBmiwJC8QjUYislzkUL9TS/ZmW9lrab8PQSKlpiXXdEWkI4pDxQbF4fDG33aveCKw+geB0vqh8iTVQphqhBbp3elZMuKl/fsbkCPloIgjIb+d8M3r7UVYC0wM9N2/FMr5NVKFL1e4r9X1GcusS0X4itFvqwuKlBYM9d1LLn1vPUnETfFKrA+sKvoJVVCuvZUyzZ7MnBLZ17djwuCrp0jb3AF+DKZUH35SvRjiMldflaHvzv5J94s7251uhTeSPx4MLmB6iogMXM="
